// <auto-generated />
using System;
using KosHome.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KosHome.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241116220628_SetupProjectStructure")]
    partial class SetupProjectStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KosHome.Domain.Entities.ApartmentImages.ApartmentImage", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ApartmentId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ImageUrl");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("apartment_images", (string)null);
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Apartments.Apartment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("SquareMeters")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.ToTable("apartments", (string)null);
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Cities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Alpha3Code");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.HasKey("Id");

                    b.ToTable("citites", (string)null);
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Countries.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Alpha3Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Alpha3Code");

                    b.HasKey("Id");

                    b.HasIndex("Alpha3Code")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdentityId")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Apartments.Apartment", b =>
                {
                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.Address", "Address", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Address");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.Description", "Description", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("Description");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.ListingType", "ListingType", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("ListingType");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.Price", "Price", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.PropertyType", "PropertyType", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("PropertyType");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.OwnsOne("KosHome.Domain.ValueObjects.Apartments.Title", "Title", b1 =>
                        {
                            b1.Property<string>("ApartmentId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("Title");

                            b1.HasKey("ApartmentId");

                            b1.ToTable("apartments");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentId");
                        });

                    b.Navigation("Address");

                    b.Navigation("Description");

                    b.Navigation("ListingType");

                    b.Navigation("Price");

                    b.Navigation("PropertyType");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Cities.City", b =>
                {
                    b.OwnsOne("KosHome.Domain.ValueObjects.Cities.CityName", "CityName", b1 =>
                        {
                            b1.Property<string>("CityId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("CityName");

                            b1.HasKey("CityId");

                            b1.ToTable("citites");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("CityName");
                });

            modelBuilder.Entity("KosHome.Domain.Entities.Countries.Country", b =>
                {
                    b.OwnsOne("KosHome.Domain.ValueObjects.Countries.CountryName", "CountryName", b1 =>
                        {
                            b1.Property<string>("CountryId")
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("Value")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("CountryName");

                            b1.HasKey("CountryId");

                            b1.ToTable("countries");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("CountryName");
                });
#pragma warning restore 612, 618
        }
    }
}
